### ISSUE TITLE
Problem with /graphql endpoint

### ISSUE THREAD

**Issue by ghost** [tim-field/graphql-wp#1]
Hi @timbofield 

I tried to use your project and installed Wordpress together with your package via composer.
Unfortunately, there is no endpoint as: `/graphql`
Could you describe how I should install it?

Cheers.

**Comment by tim-field** [comment]
Hi @tommyJS does the plugin show in the WordPress admin ?

If not check your composer.json file, it will need to be configured to install wordpress-plugins in the appropriate directory ( otherwise it will default to /vendor/ and WordPress won't see it ) See bedrocks composer.json for an example https://github.com/roots/bedrock/blob/master/composer.json 

Once the plugin is installed you'll need to ensure that permalinks are enabled. Then it should be good.

Let me know if still stuck.

**Comment by ghost** [comment]
Thank you for your answer. I made a mistake and the plugin was not visible for Wordpress. Now, it is visible and the plugin is activated. When I reach `localhost/wordpress/wp/graphql`, then I see:
`{"data":null,"errors":[{"message":"Syntax Error GraphQL request (1:1) Unexpected EOF\n\n1: \n   ^\n","locations":[{"line":1,"column":1}]}]}`
so it seems that permalinks are enabled. I put this endpoint to ChromeiQL and I see:

```
TypeError: Failed to fetch
    at TypeError (native)
    at Object.fetcher (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/js/chromeiql.js:62:18)
    at GraphiQL._fetchQuery (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/graphiql/graphiql.js:1542:16)
    at GraphiQL.componentDidMount (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/graphiql/graphiql.js:1394:12)
    at r.a.notifyAll (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:12:7291)
    at r.f.close (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:14:30976)
    at r.o.closeAll (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:15:24132)
    at r.o.perform (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:15:23578)
    at o.perform (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:15:23495)
    at o.v.perform (chrome-extension://fkkiamalmpiidkljmicmjfbieiclmeij/ext/react.min.js:15:5376)
```

Do you know what might be the cause?

**Comment by tim-field** [comment]
The Syntax error is expected, it does this with an empty query. 

So you are putting http://localhost/wordpress/wp/graphql in the endpoint field of ChromeiQL ?  I haven't tried with a localhost endpoint, but I don't see why that would be an issue. So not sure beyond that.

**Comment by ghost** [comment]
It works with `http://localhost/wordpress/wp/graphql`. Unfortunately, ChromeiQL does not take `http` as a default protocol. Thank you for the help.

**Comment by felixzapata** [comment]
Hi, I´ve a similar problem. After install the plugin and update the permalinks (using post name), I can´t find the endpoint via ChromeiQL. I´m using a virtualhost for my WordPress so the url for the endpoint is `http://mydomain/graphql`.

If I write the endpoint in the browser the response is:

```
{"errors":{"message":"Wrong query format or empty query. Either send raw query _with_ Content-Type: 'application\/json' header or send query by posting www-form-data with a query=\"query{}...\" parameter"}}
```

**Comment by felixzapata** [comment]
Nevermind, it works. 

I was wrong with the extension. If I pass a query, you have results. 

Sorry
